name: Deploy blog

on:
  push:
    branches:
      - main

jobs:
  deply:
    runs-on: ubuntu-latest
    steps:
      - name: git clone blog
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.USER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            sudo su
            sleep 1m
            cd /var/www
            rm -rf blog 
            git clone https://gitee.com/wuqinqiang/blog.git
            sudo su
            chmod -R 777 blog
            

