name: Deploy blog

on:
  push:
    branches:
      - main

jobs:
  deply:
    runs-on: ubuntu-latest

    steps:
      - name: git clone blog
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.USER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_KEY }}

          script: |
            sudo su
            cd /var/www
            rm -rf blog 
            git clone https://github.com/wuqinqiang/blog.git
            

